package com.example.hellodesigner.views;

import com.example.hellodesigner.designs.LoginDesign;
import com.example.hellodesigner.listeners.MyClickListener;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

/**
 * 
 * @author djeisonselzlein
 * 
 *         This class extends LoginDesign that is the "companion" class
 *         generated by Vaadin Designer for LoginDesign.html. It also contains
 *         the "logic" for Login view. Security is not the focus here, but the
 *         implementation and use of the Vaadin Designer.
 */
public class LoginView extends LoginDesign implements View {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Navigator navigator;

	public LoginView(Navigator nav) {
		super();
		this.navigator = nav;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		this.loginButton.addClickListener(new MyClickListener("main", this));
	}

	public Navigator getNavigator() {
		return navigator;
	}

	public TextField getUserTextField() {
		return this.login;
	}

	public PasswordField getPasswordTextField() {
		return this.password;
	}

}
