package com.example.hellodesigner.views;

import java.util.Arrays;

import com.example.hellodesigner.designs.MainDesign;
import com.example.hellodesigner.listeners.MyClickListener;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;

/**
 * 
 * @author djeisonselzlein
 * 
 * This class extends MainDesign that is the "companion"
 * class generated by Vaadin Designer. It also contains
 * the "logic" for Main view, since it access the superclass'
 * attributes and populates the controllers.
 *
 */
public class MainView extends MainDesign implements View {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Navigator navigator;

	public MainView(Navigator nav) {
		this.navigator = nav;
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		this.favoriteSport.addItems(Arrays.asList("Soccer", "Volleyball", "Basketball", "Football"));
		this.logoutButton.addClickListener(new MyClickListener("", navigator));
	}

}
